language: node_js
node_js:
  - "8"
env:
  NODE_ENV: PRD
before_deploy: sudo pip install awscli
deploy:
  - provider: script
    skip_cleanup: true
    script: AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY npm run upload
